version: "3.0"

services:
  nginx:
    container_name: laravel-nginx
    image: nginx:1.17-alpine
    ports:
      - 8002:80
    depends_on:
      - fpm
      - mysql
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    tty: true
  fpm:
    container_name: laravel-fpm
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - ./:/var/www/laravel
  mysql:
    container_name: laravel-mysql
    image: mysql:8.0
    ports:
      - 33062:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=qwerty
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
